/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.meia;

import clases.*;
import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import proyecto.meia.listas.*;

/**
 *
 * @author AxelAlejandro
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    TimerHilo timerHilo = null;
    
    JPanel panelCorreo = null;
    JLabel deDato = null;
    JLabel asuntoDato = null;
    org.edisoncor.gui.button.ButtonSeven verCorreo = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleBar1 = new org.edisoncor.gui.varios.TitleBar();
        jPanel1 = new javax.swing.JPanel();
        lblTipoUsuario = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        tabbedPaneHeader4 = new org.edisoncor.gui.tabbedPane.TabbedPaneHeader();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        epMensajeEntrada = new javax.swing.JEditorPane();
        lblDeEntrada = new org.edisoncor.gui.label.LabelHeader();
        lblAsuntoEntrada = new org.edisoncor.gui.label.LabelHeader();
        lpCorreosEntrada1 = new javax.swing.JScrollPane();
        lpCorreosEntrada = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblPara = new org.edisoncor.gui.label.LabelHeader();
        lblAsuntoEnviado = new org.edisoncor.gui.label.LabelHeader();
        jScrollPane2 = new javax.swing.JScrollPane();
        epMensajeEnviado = new javax.swing.JEditorPane();
        lpCorreosSalida1 = new javax.swing.JScrollPane();
        lpCorreosSalida = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        cbrUsuarios = new org.edisoncor.gui.comboBox.ComboBoxRound();
        jLabel2 = new javax.swing.JLabel();
        txtAsuntoEnviar = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDetalleEnviar = new javax.swing.JEditorPane();
        buttonSeven1 = new org.edisoncor.gui.button.ButtonSeven();
        lblNombreArchivo = new javax.swing.JLabel();
        buttonAction1 = new org.edisoncor.gui.button.ButtonAction();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreGrupo = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        txtUsuarioExterno = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        jPanel2 = new javax.swing.JPanel();
        btnEditarUsuarios = new org.edisoncor.gui.button.ButtonSeven();
        btnAgregarUsuarios = new org.edisoncor.gui.button.ButtonSeven();
        btnEliminarUsuarios = new org.edisoncor.gui.button.ButtonSeven();
        btnBuscarUsuarios = new org.edisoncor.gui.button.ButtonSeven();
        jPanel4 = new javax.swing.JPanel();
        btnEditarListas = new org.edisoncor.gui.button.ButtonSeven();
        btnBuscarListas = new org.edisoncor.gui.button.ButtonSeven();
        btnEliminarListas = new org.edisoncor.gui.button.ButtonSeven();
        btnAgregarListas = new org.edisoncor.gui.button.ButtonSeven();
        btnEliminarUsuariosListas = new org.edisoncor.gui.button.ButtonSeven();
        jPanel3 = new javax.swing.JPanel();
        btnCerrarSesion = new org.edisoncor.gui.button.ButtonIcon();
        btnHacerBackup = new org.edisoncor.gui.button.ButtonSeven();
        btnRestaurarBackup = new org.edisoncor.gui.button.ButtonSeven();
        buttonSeven2 = new org.edisoncor.gui.button.ButtonSeven();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setUndecorated(true);

        titleBar1.setBackground(new java.awt.Color(153, 153, 153));
        titleBar1.setTitulo("Principal");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        lblTipoUsuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblTipoUsuario.setText("jLabel1");

        lblNombreUsuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreUsuario.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoUsuario)
                    .addComponent(lblNombreUsuario))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        epMensajeEntrada.setDisabledTextColor(new java.awt.Color(29, 29, 29));
        epMensajeEntrada.setEnabled(false);
        jScrollPane1.setViewportView(epMensajeEntrada);

        lblDeEntrada.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDeEntrada.setText("De:");

        lblAsuntoEntrada.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAsuntoEntrada.setText("Asunto:");

        lpCorreosEntrada1.setBackground(new java.awt.Color(153, 153, 153));
        lpCorreosEntrada1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lpCorreosEntrada1.setAutoscrolls(true);

        lpCorreosEntrada.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout lpCorreosEntradaLayout = new javax.swing.GroupLayout(lpCorreosEntrada);
        lpCorreosEntrada.setLayout(lpCorreosEntradaLayout);
        lpCorreosEntradaLayout.setHorizontalGroup(
            lpCorreosEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );
        lpCorreosEntradaLayout.setVerticalGroup(
            lpCorreosEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );

        lpCorreosEntrada1.setViewportView(lpCorreosEntrada);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lpCorreosEntrada1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDeEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAsuntoEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblDeEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAsuntoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE))
            .addComponent(lpCorreosEntrada1)
        );

        tabbedPaneHeader4.addTab("Bandeja de Entrada", jPanel5);

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));

        lblPara.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPara.setText("Para:");

        lblAsuntoEnviado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAsuntoEnviado.setText("Asunto:");

        epMensajeEnviado.setDisabledTextColor(new java.awt.Color(29, 29, 29));
        epMensajeEnviado.setEnabled(false);
        jScrollPane2.setViewportView(epMensajeEnviado);

        lpCorreosSalida.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout lpCorreosSalidaLayout = new javax.swing.GroupLayout(lpCorreosSalida);
        lpCorreosSalida.setLayout(lpCorreosSalidaLayout);
        lpCorreosSalidaLayout.setHorizontalGroup(
            lpCorreosSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );
        lpCorreosSalidaLayout.setVerticalGroup(
            lpCorreosSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );

        lpCorreosSalida1.setViewportView(lpCorreosSalida);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(lpCorreosSalida1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAsuntoEnviado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblPara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAsuntoEnviado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2))
            .addComponent(lpCorreosSalida1)
        );

        tabbedPaneHeader4.addTab("Bandeja de Salida", jPanel6);

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setText("Para:");

        jCheckBox1.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBox1.setText("¿Enviar a una Lista de Distribución?");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Asunto: ");

        jLabel3.setText("Mensaje");

        jScrollPane3.setViewportView(txtDetalleEnviar);

        buttonSeven1.setText("Seleccionar Archivo");
        buttonSeven1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeven1ActionPerformed(evt);
            }
        });

        lblNombreArchivo.setText("Nombre del Archivo");

        buttonAction1.setText("Enviar");
        buttonAction1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction1ActionPerformed(evt);
            }
        });

        jCheckBox2.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBox2.setText("Enviar a otro gruo");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));

        jLabel4.setText("Grupo");

        jLabel5.setText("Usuario");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUsuarioExterno, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUsuarioExterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAsuntoEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jCheckBox1)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(cbrUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(buttonSeven1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNombreArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonAction1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addGap(7, 7, 7)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbrUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtAsuntoEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSeven1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(buttonAction1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        tabbedPaneHeader4.addTab("Nuevo Mensaje", jPanel7);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        btnEditarUsuarios.setText("Editar");

        btnAgregarUsuarios.setText("Agregar");
        btnAgregarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUsuariosActionPerformed(evt);
            }
        });

        btnEliminarUsuarios.setText("Eliminar");

        btnBuscarUsuarios.setText("Buscar");
        btnBuscarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgregarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(714, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(btnAgregarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnEditarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnEliminarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnBuscarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPaneHeader4.addTab("Usuarios", jPanel2);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setPreferredSize(new java.awt.Dimension(328, 326));

        btnEditarListas.setText("Editar");

        btnBuscarListas.setText("Buscar");
        btnBuscarListas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarListasActionPerformed(evt);
            }
        });

        btnEliminarListas.setText("Eliminar");

        btnAgregarListas.setText("Agregar");
        btnAgregarListas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarListasActionPerformed(evt);
            }
        });

        btnEliminarUsuariosListas.setText("Eliminar un usuario");
        btnEliminarUsuariosListas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuariosListasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgregarListas, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarListas, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarListas, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarListas, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarUsuariosListas, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(731, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnAgregarListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnEditarListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnEliminarListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnBuscarListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btnEliminarUsuariosListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPaneHeader4.addTab("Listas de Distribución", jPanel4);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setPreferredSize(new java.awt.Dimension(328, 326));

        btnCerrarSesion.setForeground(new java.awt.Color(29, 29, 29));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logout.png"))); // NOI18N
        btnCerrarSesion.setText("Modificar");
        btnCerrarSesion.setToolTipText("Cerrar Sesión");
        btnCerrarSesion.setPreferredSize(new java.awt.Dimension(116, 25));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        btnHacerBackup.setText("Realizar Backup");
        btnHacerBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHacerBackupActionPerformed(evt);
            }
        });

        btnRestaurarBackup.setText("Restaurar Backup");
        btnRestaurarBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarBackupActionPerformed(evt);
            }
        });

        buttonSeven2.setText("Actualizar Bandejas");
        buttonSeven2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeven2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHacerBackup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRestaurarBackup, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(buttonSeven2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(715, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHacerBackup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnRestaurarBackup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(buttonSeven2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabbedPaneHeader4.addTab("Otros", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(titleBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabbedPaneHeader4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPaneHeader4, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarBandejas() throws Exception
    {
        // Carga de correos a la bandeja de entrada
        
        ArbolBinario arbol = new ArbolBinario(new File(Utilidades.ArchivoArbol), new File(Utilidades.ArchivoDescriptorArbol));
        List<DatoArbol> datos = arbol.buscarDatos();
        lpCorreosEntrada.removeAll();
        lpCorreosSalida.removeAll();
        PanelCorreos panel = null;
        PanelEnviados panelE = null;
        AccionVerCorreo verCorreoAccion = new AccionVerCorreo(datos, this);
        AccionEliminar accionEliminar = new AccionEliminar(datos, this);
        int contador = 100;
        int contEnviados = 0;
        int contRecibidos = 0;
        for (int i = 0; i < datos.size(); i++)
        {
            if (datos.get(i).UsuarioReceptor.equals(Utilidades.usuarioActual.NombreUsuario))
            {
                panel = new PanelCorreos(i, datos);
                panel.btnVer.addActionListener(verCorreoAccion);
                panel.btnEliminarCorreo.addActionListener(accionEliminar);
                panel.lblAsunto.setText(datos.get(i).Asunto);
                panel.lblDe.setText(datos.get(i).UsuarioEmisor);
                panel.setLocation(0, contador * contRecibidos);
                contRecibidos++;
                lpCorreosEntrada.add(panel);
                lpCorreosEntrada.repaint();
            }
            if (datos.get(i).UsuarioEmisor.equals(Utilidades.usuarioActual.NombreUsuario))
            {
                panelE = new PanelEnviados(i, datos);
                panelE.btnVer.addActionListener(verCorreoAccion);
                panelE.btnEliminarCorreo.addActionListener(accionEliminar);
                panelE.lblAsunto.setText(datos.get(i).Asunto);
                panelE.lblDe.setText(datos.get(i).UsuarioReceptor);
                panelE.setLocation(0, contador * contEnviados);
                contEnviados++;
                lpCorreosSalida.add(panelE);
                lpCorreosSalida.repaint();
            }
        }
    }
    
    
    public Principal() throws Exception {
        initComponents();
        this.setLocationRelativeTo(null);
        AccionCerrar closeAction = new AccionCerrar(this);
        this.titleBar1.addCloseAction(closeAction);
        lblTipoUsuario.setText(Utilidades.usuarioActual.Rol);
        lblNombreUsuario.setText(Utilidades.usuarioActual.NombreUsuario);
        
        cargarBandejas();
        int i = 1;
        ManejoArchivosApilo usuarios = new ManejoArchivosApilo(new File(Utilidades.ArchivoUsuarios), new File(Utilidades.ArchivoDescriptorUsuarios));
        int tamanio = Integer.parseInt(usuarios.obtenerDescriptor(6)) + Integer.parseInt(usuarios.obtenerDescriptor(7));
        String[] arrayUsuarios = new String[tamanio];
        i = 1;
        String dato = "";
        while (i <= tamanio)
        {
            dato = usuarios.obtener(i).split("\\|")[0];
            cbrUsuarios.addItem(usuarios.obtener(i).split("\\|")[0]);
            i++;
        }
        timerHilo = new TimerHilo("", "grupo1");
        timerHilo.Start();
    }
    
    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        LoginForm LoginNuevo = new LoginForm();
        LoginNuevo.show();
        Utilidades.usuarioActual = null;
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnHacerBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHacerBackupActionPerformed
        // TODO add your handling code here:
        try
        {
            JFileChooser chooser = new JFileChooser();
            chooser.setCurrentDirectory(new java.io.File("."));
            chooser.setDialogTitle("Backup");
            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            chooser.setAcceptAllFileFilterUsed(false);
            if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) 
            {
                File copia = new File(chooser.getSelectedFile() + "\\MEIA_Backup\\");
                Utilidades.copiar_Directorios(new File(Utilidades.DirectorioPrincipal), copia);
                ManejoArchivosApilo BackupDescriptor = new ManejoArchivosApilo(new File(Utilidades.ArchivoBitacoraBackup), new File(Utilidades.ArchivoDescriptorBitacoraBackup));
                Date fechaActual = new Date();
                String fecha = Utilidades.formato.format(fechaActual);
                Backup Otrogato = new Backup(fecha, copia.getPath(), Utilidades.usuarioActual.NombreUsuario, true);
                BackupDescriptor.guardarEnApilo(Otrogato);
                BackupDescriptor.actualizarDescriptor(1, 0, "Ubicacion|Usuario|FechaBackup|Status");
            }
           
        }
        catch(Exception ex)
        {
            
        }
    }//GEN-LAST:event_btnHacerBackupActionPerformed

    private void btnRestaurarBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarBackupActionPerformed
        // TODO add your handling code here:
        try
        {
            JFileChooser chooser = new JFileChooser();
            chooser.setCurrentDirectory(new java.io.File("."));
            chooser.setDialogTitle("Backup");
            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            chooser.setAcceptAllFileFilterUsed(false);
            if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION)
            {
                File copia = new File(chooser.getSelectedFile() + "\\MEIA_Backup\\");
                    Utilidades.copiar_Directorios(copia,new File(Utilidades.DirectorioPrincipal));
                }

        }
        catch(Exception ex)
        {

        }
    }//GEN-LAST:event_btnRestaurarBackupActionPerformed

    private void btnAgregarListasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarListasActionPerformed
        // TODO add your handling code here:
        try {
            Agregar agregarLista = new Agregar();
            agregarLista.show();
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAgregarListasActionPerformed

    private void btnBuscarListasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarListasActionPerformed
        try {
            // TODO add your handling code here:
            Buscar buscar = new Buscar();
            buscar.show();
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarListasActionPerformed

    private void btnEliminarUsuariosListasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuariosListasActionPerformed
        // TODO add your handling code here:
        try
        {
            EliminarUsuario eliminar = new EliminarUsuario();
            eliminar.show();
            this.dispose();
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_btnEliminarUsuariosListasActionPerformed

    private void btnAgregarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarUsuariosActionPerformed

    private void btnBuscarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarUsuariosActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        cbrUsuarios.removeAllItems();
        if (jCheckBox1.isSelected())
        {
            try {
                ManejoArchivosSecuencial manejoLista = new ManejoArchivosSecuencial(new File(Utilidades.ArchivoListasDeDistribucion), new File(Utilidades.ArchivoDescriptorListasDeDistribucion),
                        new File(Utilidades.ArchivoListasDeDistribucionSecuencial), new File(Utilidades.ArchivoDescriptorListasDeDistribucionSecuencial));
                List<String> datos = new ArrayList();
                datos = manejoLista.obtenerListaPorUsuario(Utilidades.usuarioActual.NombreUsuario);
                int i = 0; String dato;
                while (i < datos.size())
                {
                    dato = datos.get(i).split("\\|")[0];
                    cbrUsuarios.addItem(datos.get(i).split("\\|")[0]);
                    i++;
                }
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            try {
                int i = 1;
                ManejoArchivosApilo usuarios = new ManejoArchivosApilo(new File(Utilidades.ArchivoUsuarios), new File(Utilidades.ArchivoDescriptorUsuarios));
                int tamanio = Integer.parseInt(usuarios.obtenerDescriptor(6)) + Integer.parseInt(usuarios.obtenerDescriptor(7));
                String[] arrayUsuarios = new String[tamanio];
                i = 1;
                String dato = "";
                while (i <= tamanio)
                {
                    dato = usuarios.obtener(i).split("\\|")[0];
                    cbrUsuarios.addItem(usuarios.obtener(i).split("\\|")[0]);
                    i++;
                }
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void buttonSeven1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeven1ActionPerformed
        // TODO add your handling code here:
        try
        {
            JFileChooser chooser = new JFileChooser();
            chooser.setDialogTitle("Seleccionar Archivo");
            if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) 
            {
                File copia = new File("C:\\MEIA\\archivos\\" + chooser.getSelectedFile().getName());
                Utilidades.Copia_archivos(new File(chooser.getSelectedFile().getAbsolutePath()), copia);
                adjunto = "C:\\MEIA\\archivos\\" + chooser.getSelectedFile().getName();
            }
           
        }
        catch(Exception ex)
        {
            
        }
    }//GEN-LAST:event_buttonSeven1ActionPerformed
    String adjunto = "0";
    ArbolBinario arbol = new ArbolBinario(new File(Utilidades.ArchivoArbol), new File(Utilidades.ArchivoDescriptorArbol));
    private void buttonAction1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction1ActionPerformed
        // TODO add your handling code here:
        try
        {
            if (jCheckBox1.isSelected() && !jCheckBox2.isSelected()) {
                ManejoArchivosIndizado  lol = new ManejoArchivosIndizado(new File(Utilidades.ArchivoIndice), new File(Utilidades.ArchivoDescriptorIndice), 
                    new File(Utilidades.ArchivoMaestro), new File(Utilidades.ArchivoDescriptorMaestro));  
                List<String> Usuarios = lol.obtener(Utilidades.usuarioActual.NombreUsuario, cbrUsuarios.getSelectedItem().toString());
                Date fecha = new Date();
                DatoArbol dato = null;
                for (int i = 0; i < Usuarios.size(); i++) {
                    dato = new DatoArbol(Utilidades.usuarioActual.NombreUsuario, Usuarios.get(i) , Utilidades.formato.format(fecha), txtAsuntoEnviar.getText(),
                    txtDetalleEnviar.getText(), adjunto, true);
                    arbol.agregarFisico(dato,Utilidades.usuarioActual.NombreUsuario + "|" + Usuarios.get(i) + "|" +Utilidades.formato.format(fecha) );
                    arbol.actualizarDescriptor(1, 0, "padre^izquierda^derecha^llave^dato");
                }
            }
            else
            {
                boolean continuar = true;
                if (jCheckBox2.isSelected())
                {
                    ConexionBaseDatos con = new ConexionBaseDatos();
                    con.insertar(txtNombreGrupo.getText(), Utilidades.usuarioActual.NombreUsuario, txtUsuarioExterno.getText(), txtAsuntoEnviar.getText(),
                        txtDetalleEnviar.getText(), "0");
                    Thread.sleep(45000);
                    List<DatosBD> datos = con.obtener(txtNombreGrupo.getText(), Utilidades.usuarioActual.NombreUsuario, txtUsuarioExterno.getText());
                    if (!"si".equals(datos.get(datos.size() - 1).Estatus))
                    {
                        continuar = false;
                    }
                }
                if (continuar)
                {
                    Date fecha = new Date();
                    DatoArbol dato = new DatoArbol(Utilidades.usuarioActual.NombreUsuario, cbrUsuarios.getSelectedItem().toString(), Utilidades.formato.format(fecha), txtAsuntoEnviar.getText(),
                    txtDetalleEnviar.getText(), adjunto, true);
                    arbol.agregarFisico(dato, Utilidades.usuarioActual.NombreUsuario + "|" + cbrUsuarios.getSelectedItem().toString() + "|" +Utilidades.formato.format(fecha));
                    arbol.actualizarDescriptor(1, 0, "padre^izquierda^derecha^llave^dato");
                }
            }
            jCheckBox1.setSelected(false); jCheckBox2.setSelected(false);
            txtAsuntoEnviar.setText("");
            txtDetalleEnviar.setText("");
            txtNombreGrupo.setText("");
            txtUsuarioExterno.setText("");
            adjunto = "0";
            cargarBandejas();
            JOptionPane.showMessageDialog(this, "Registro Insertado");
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_buttonAction1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox2.isSelected())
        {
            cbrUsuarios.setEnabled(false);
            jCheckBox1.setEnabled(false);
            jPanel7.setVisible(true);
        }
        else
        {
            cbrUsuarios.setEnabled(true);
            jCheckBox1.setEnabled(true);
            jPanel7.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void buttonSeven2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeven2ActionPerformed
        try {
            // TODO add your handling code here:
            cargarBandejas();
        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonSeven2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Principal().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonSeven btnAgregarListas;
    private org.edisoncor.gui.button.ButtonSeven btnAgregarUsuarios;
    private org.edisoncor.gui.button.ButtonSeven btnBuscarListas;
    private org.edisoncor.gui.button.ButtonSeven btnBuscarUsuarios;
    private org.edisoncor.gui.button.ButtonIcon btnCerrarSesion;
    private org.edisoncor.gui.button.ButtonSeven btnEditarListas;
    private org.edisoncor.gui.button.ButtonSeven btnEditarUsuarios;
    private org.edisoncor.gui.button.ButtonSeven btnEliminarListas;
    private org.edisoncor.gui.button.ButtonSeven btnEliminarUsuarios;
    private org.edisoncor.gui.button.ButtonSeven btnEliminarUsuariosListas;
    private org.edisoncor.gui.button.ButtonSeven btnHacerBackup;
    private org.edisoncor.gui.button.ButtonSeven btnRestaurarBackup;
    private org.edisoncor.gui.button.ButtonAction buttonAction1;
    private org.edisoncor.gui.button.ButtonSeven buttonSeven1;
    private org.edisoncor.gui.button.ButtonSeven buttonSeven2;
    private org.edisoncor.gui.comboBox.ComboBoxRound cbrUsuarios;
    public javax.swing.JEditorPane epMensajeEntrada;
    public javax.swing.JEditorPane epMensajeEnviado;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public org.edisoncor.gui.label.LabelHeader lblAsuntoEntrada;
    public org.edisoncor.gui.label.LabelHeader lblAsuntoEnviado;
    public org.edisoncor.gui.label.LabelHeader lblDeEntrada;
    private javax.swing.JLabel lblNombreArchivo;
    private javax.swing.JLabel lblNombreUsuario;
    public org.edisoncor.gui.label.LabelHeader lblPara;
    private javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JPanel lpCorreosEntrada;
    private javax.swing.JScrollPane lpCorreosEntrada1;
    private javax.swing.JPanel lpCorreosSalida;
    private javax.swing.JScrollPane lpCorreosSalida1;
    private org.edisoncor.gui.tabbedPane.TabbedPaneHeader tabbedPaneHeader4;
    private org.edisoncor.gui.varios.TitleBar titleBar1;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtAsuntoEnviar;
    private javax.swing.JEditorPane txtDetalleEnviar;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtNombreGrupo;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtUsuarioExterno;
    // End of variables declaration//GEN-END:variables
}
