/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.meia;

import clases.*;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author AxelAlejandro
 */
public class Registro extends javax.swing.JFrame {

    private String direccionImagen = "";
    private boolean continuarGuardado = false;
    
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
        AccionCerrar closeAction = new AccionCerrar(new LoginForm(), this);
        this.titleBar1.addCloseAction(closeAction);
        ImageIcon avatar = new ImageIcon(getClass().getResource("/imagenes/user-default.png"));
        Icon icono = new ImageIcon(avatar.getImage().getScaledInstance(piUserImg.getWidth(), piUserImg.getWidth(), Image.SCALE_DEFAULT));
        piUserImg.setIcon(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleBar1 = new org.edisoncor.gui.varios.TitleBar();
        pbSeguridad = new org.edisoncor.gui.progressBar.ProgressBarRound();
        labelTask1 = new org.edisoncor.gui.label.LabelTask();
        piUserImg = new javax.swing.JLabel();
        btnCancelar = new org.edisoncor.gui.button.ButtonSeven();
        jLabel8 = new javax.swing.JLabel();
        lblMayus = new javax.swing.JLabel();
        txtNombre = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        lblCantidadLetras = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNumeros = new javax.swing.JLabel();
        txtApellido = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        jLabel2 = new javax.swing.JLabel();
        lblSimbolos = new javax.swing.JLabel();
        txtContrasenia = new org.edisoncor.gui.passwordField.PasswordFieldRoundIcon();
        txtUsername = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        lblCorreoValido = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTelefono = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        jLabel5 = new javax.swing.JLabel();
        btnSeleccionarArchivo = new org.edisoncor.gui.button.ButtonSeven();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCorreoAlterno = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        btnRegistro = new org.edisoncor.gui.button.ButtonAction();
        jdcFechaNacimiento = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        titleBar1.setTitulo("Registrarse");

        pbSeguridad.setToolTipText("Nivel de Seguridad:\n Rojo --> Muy Insegura\n, Amarillo --> Insegura\n, Azul --> Segura\n, Verde --> Muy Segura");
        pbSeguridad.setBorde(0.0F);
        pbSeguridad.setString("Contraseña muy insegura");
        pbSeguridad.setStringPainted(true);

        labelTask1.setText("Registrarse");
        labelTask1.setDescription("Registro de un nuevo usuario");
        labelTask1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N

        btnCancelar.setText("Cancelar");
        btnCancelar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel8.setText("La contraseña debe tener:");

        lblMayus.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        lblMayus.setText("Mayusculas");

        txtNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 2));
        txtNombre.setToolTipText("Primer Nombre");
        txtNombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N

        lblCantidadLetras.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        lblCantidadLetras.setText("Minimo 6 letras");

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel1.setText("Nombre");

        lblNumeros.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        lblNumeros.setText("Un número");

        txtApellido.setToolTipText("Apellidos");
        txtApellido.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel2.setText("Apellido");

        lblSimbolos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        lblSimbolos.setText("Total de simbolos ingresados");

        txtContrasenia.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 2));
        txtContrasenia.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        txtContrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContraseniaKeyReleased(evt);
            }
        });

        txtUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 2));
        txtUsername.setToolTipText("Nombre de usuario");
        txtUsername.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsernameKeyReleased(evt);
            }
        });

        lblCorreoValido.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        lblCorreoValido.setText("Correo electrónico no valido");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel3.setText("Nombre de Usuario");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel4.setText("Fecha de Nacimiento");

        txtTelefono.setToolTipText("Número de teléfono");
        txtTelefono.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel5.setText("Número de Teléfono");

        btnSeleccionarArchivo.setText("Seleccionar Imagen");
        btnSeleccionarArchivo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnSeleccionarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarArchivoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel6.setText("Contraseña");

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel7.setText("Correo electrónico alterno");

        txtCorreoAlterno.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 2));
        txtCorreoAlterno.setToolTipText("Correo electrónico alterno");
        txtCorreoAlterno.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        txtCorreoAlterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorreoAlternoKeyReleased(evt);
            }
        });

        btnRegistro.setText("Registarse");
        btnRegistro.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTask1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCorreoValido)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSeleccionarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCorreoAlterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pbSeguridad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCantidadLetras)
                                            .addComponent(lblMayus)
                                            .addComponent(lblNumeros)
                                            .addComponent(lblSimbolos)))
                                    .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(piUserImg, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jdcFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTask1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(7, 7, 7)
                        .addComponent(jdcFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(piUserImg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeleccionarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMayus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCantidadLetras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumeros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSimbolos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreoAlterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(lblCorreoValido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        LoginForm login = new LoginForm();
        login.show();
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtContraseniaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseniaKeyReleased
        try {
            if (Utilidades.comprobarCaracteres(txtContrasenia.getText(), "ABCDEFGHIJKLMNÑOPQRSTUVWXYZ") >= 1)
                lblMayus.setForeground(Utilidades.Verde);
            else
                lblMayus.setForeground(Utilidades.Rojo);

            if (Utilidades.comprobarCaracteres(txtContrasenia.getText(), "0123456789") >= 1)
                lblNumeros.setForeground(Utilidades.Verde);
            else
                lblNumeros.setForeground(Utilidades.Rojo);

            if (txtContrasenia.getText().length() >= 6)
                lblCantidadLetras.setForeground(Utilidades.Verde);
            else
                lblCantidadLetras.setForeground(Utilidades.Rojo);

            if (Utilidades.comprobarCaracteres(txtContrasenia.getText(), "[/¿?%$#]") >= 1)
                lblSimbolos.setForeground(Utilidades.Verde);
            else
                lblSimbolos.setForeground(Utilidades.Rojo);
            List<String> resultados = Utilidades.obtenerDeArchivoContrasenia(Utilidades.ArchivoResultados);
            List<String> puntuaciones = Utilidades.obtenerDeArchivoContrasenia(Utilidades.ArchivoPuntuacion);
            String password = "";
            if (txtContrasenia.getText() != null)
            {
                password = txtContrasenia.getText();
            }
            int seguridad = Utilidades.ContraseñaComprobar(password, puntuaciones, resultados);
            switch (seguridad) {
                case 0:
                    pbSeguridad.setForeground(Utilidades.Rojo);
                    pbSeguridad.setValue(25);
                    pbSeguridad.setString("Contraseña muy insegura");
                    txtContrasenia.setForeground(Utilidades.Rojo);
                    txtContrasenia.setBackground(Utilidades.RojoClaro);
                    txtContrasenia.setColorDeBorde(Utilidades.Rojo);
                    break;
                case 1:
                    pbSeguridad.setForeground(Utilidades.Amarillo);
                    pbSeguridad.setValue(50);
                    pbSeguridad.setString("Contraseña insegura");
                    txtContrasenia.setForeground(Utilidades.Amarillo);
                    txtContrasenia.setBackground(Utilidades.AmarilloClaro);
                    txtContrasenia.setColorDeBorde(Utilidades.Amarillo);
                    break;
                case 2:
                    pbSeguridad.setForeground(Utilidades.Azul);
                    pbSeguridad.setValue(75);
                    pbSeguridad.setString("Contraseña segura");
                    txtContrasenia.setForeground(Utilidades.Azul);
                    txtContrasenia.setBackground(Utilidades.AzulClaro);
                    txtContrasenia.setColorDeBorde(Utilidades.Azul);
                    break;
                case 3:
                    pbSeguridad.setForeground(Utilidades.Verde);
                    pbSeguridad.setValue(100);
                    pbSeguridad.setString("Contraseña muy segura");
                    txtContrasenia.setForeground(Utilidades.Verde);
                    txtContrasenia.setBackground(Utilidades.VerdeClaro);
                    txtContrasenia.setColorDeBorde(Utilidades.Verde);
                    break;
                default:
                    break;
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
        catch (Exception exc)
        {
            pbSeguridad.setForeground(Utilidades.Rojo);
            pbSeguridad.setValue(25);
            pbSeguridad.setString("Contraseña muy insegura");
            txtContrasenia.setForeground(Utilidades.Rojo);
            txtContrasenia.setBackground(Utilidades.RojoClaro);
            txtContrasenia.setColorDeBorde(Utilidades.Rojo);
        }
    }//GEN-LAST:event_txtContraseniaKeyReleased

    private void txtUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyReleased
        if (Utilidades.comprobarUsuario(txtUsername.getText())  || Utilidades.comprobarCaracteres(txtUsername.getText(), "ABCDEFGHIJKLMÑOPQRSTUVWXYZabcdefghijklmnñopqrstuvwxyz") < 1 && 
                    Utilidades.comprobarCaracteres(txtUsername.getText(), "0123456789") < 1 && Utilidades.comprobarCaracteres(txtUsername.getText(), "[/¿?%$#]") < 1)
        {
            txtUsername.setForeground(Utilidades.Rojo);
            txtUsername.setColorDeBorde(Utilidades.Rojo);
            txtUsername.setBackground(Utilidades.RojoClaro);
        }
        else
        {
            txtUsername.setForeground(Utilidades.Verde);
            txtUsername.setColorDeBorde(Utilidades.Verde);
            txtUsername.setBackground(Utilidades.VerdeClaro);
        }
    }//GEN-LAST:event_txtUsernameKeyReleased

    private void btnSeleccionarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarArchivoActionPerformed
        try
        {
            JFileChooser selector = new JFileChooser();
            selector.setFileFilter(Utilidades.filtro);
            selector.showDialog(this, "Elegir");
            File imagen = selector.getSelectedFile();
            String img = imagen.getAbsolutePath();
            direccionImagen = img;
            ImageIcon avatar = new ImageIcon(img);
            Icon icono = new ImageIcon(avatar.getImage().getScaledInstance(piUserImg.getWidth(), piUserImg.getWidth(), Image.SCALE_DEFAULT));
            piUserImg.setIcon(icono);
            this.repaint();
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningún archivo");
        }
    }//GEN-LAST:event_btnSeleccionarArchivoActionPerformed

    private void txtCorreoAlternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoAlternoKeyReleased
        if (Utilidades.comprobarCorreo(txtCorreoAlterno.getText()))
        {
            txtCorreoAlterno.setBackground(Utilidades.VerdeClaro);
            txtCorreoAlterno.setForeground(Utilidades.Verde);
            txtCorreoAlterno.setColorDeBorde(Utilidades.Verde);
        }
        else
        {
            txtCorreoAlterno.setBackground(Utilidades.RojoClaro);
            txtCorreoAlterno.setForeground(Utilidades.Rojo);
            txtCorreoAlterno.setColorDeBorde(Utilidades.Rojo);
        }
    }//GEN-LAST:event_txtCorreoAlternoKeyReleased

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        try
        {
            List<String> resultados = Utilidades.obtenerDeArchivoContrasenia(Utilidades.ArchivoResultados);
            List<String> puntuaciones = Utilidades.obtenerDeArchivoContrasenia(Utilidades.ArchivoPuntuacion);
            if ("".equals(txtNombre.getText()) || "".equals(txtApellido.getText()) || jdcFechaNacimiento.getDate() == null || "".equals(txtTelefono.getText()) ||
                "".equals(txtUsername.getText()) || "".equals(txtContrasenia.getText()) || "".equals(txtCorreoAlterno.getText()))
            {
                JOptionPane.showMessageDialog(this, "Debe llenar todos los campos");
            }
            else if (!Utilidades.comprobarCorreo(txtCorreoAlterno.getText()))
            {
                JOptionPane.showMessageDialog(this, "El correo electrónico debe tener un formato correcto");
            }
            else if (Utilidades.ContraseñaComprobar(txtContrasenia.getText(), puntuaciones, resultados) == 0 || 
                    Utilidades.ContraseñaComprobar(txtContrasenia.getText(), puntuaciones, resultados) == 1)
            {
                JOptionPane.showMessageDialog(this, "La contraseña que ingreso no fue aceptada");
            }
            else if (Utilidades.comprobarUsuario(txtUsername.getText()))
            {
                JOptionPane.showMessageDialog(this, "El usuario ya se encuentra registrado");
            }
            else
            {
                if ("".equals(direccionImagen))
                {
                    if (JOptionPane.showConfirmDialog(this, "¿Seguro que desea guardar su perfil con la imagen por defecto?", "Continuar", 0) == 0)
                    {
                        direccionImagen = getClass().getResource("/imagenes/user-default.png").getPath().substring(1).replace("%20", " ");
                        continuarGuardado = true;
                    }
                    else
                    {
                        continuarGuardado = false;
                    }
                }
                else
                {
                    continuarGuardado = true;
                }
                if (continuarGuardado)
                {
                    ManejoArchivosApilo nuevoUsuario = new ManejoArchivosApilo(new File(Utilidades.ArchivoUsuarios), new File(Utilidades.ArchivoDescriptorUsuarios));
                    String tipoUsuario = "Administrador";
                    File archivoPrueba = new File(Utilidades.ArchivoUsuarios);
                    if (archivoPrueba.exists())
                    {
                        tipoUsuario = "Empleado";
                    }
                    String direccionNuevaImagen = Utilidades.RutaFotografias + txtUsername.getText() + "." + direccionImagen.split("\\.")[direccionImagen.split("\\.").length - 1];
                    Utilidades.Copia_archivos(new File(direccionImagen), new File(direccionNuevaImagen));
                    Utilidades.usuarioActual = new Usuario(txtUsername.getText(), txtNombre.getText(), txtApellido.getText(), 
                    txtContrasenia.getText(), tipoUsuario, Utilidades.fechaNormal(jdcFechaNacimiento), txtCorreoAlterno.getText(),
                    txtTelefono.getText(), direccionNuevaImagen, true);
                    nuevoUsuario.guardarEnApilo(Utilidades.usuarioActual);
                    nuevoUsuario.actualizarDescriptor(1, 0, "NombreUsuario|Nombre|Apellido|Contraseña|Rol|FechaDeNacimiento|CorreoAlterno|Telefono|FotoURL|Estatus");
                    JOptionPane.showMessageDialog(this, "Para continuar debe registrarse");
                    LoginForm login = new LoginForm();
                    login.show();
                    this.dispose();
                }
            }
        }
        catch (IOException | HeadlessException ex)
        {
            JOptionPane.showMessageDialog(this, ex);
            ex.printStackTrace();
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, ex);
            ex.printStackTrace();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonSeven btnCancelar;
    private org.edisoncor.gui.button.ButtonAction btnRegistro;
    private org.edisoncor.gui.button.ButtonSeven btnSeleccionarArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private com.toedter.calendar.JDateChooser jdcFechaNacimiento;
    private org.edisoncor.gui.label.LabelTask labelTask1;
    private javax.swing.JLabel lblCantidadLetras;
    private javax.swing.JLabel lblCorreoValido;
    private javax.swing.JLabel lblMayus;
    private javax.swing.JLabel lblNumeros;
    private javax.swing.JLabel lblSimbolos;
    private org.edisoncor.gui.progressBar.ProgressBarRound pbSeguridad;
    private javax.swing.JLabel piUserImg;
    private org.edisoncor.gui.varios.TitleBar titleBar1;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtApellido;
    private org.edisoncor.gui.passwordField.PasswordFieldRoundIcon txtContrasenia;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtCorreoAlterno;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtNombre;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtTelefono;
    private org.edisoncor.gui.textField.TextFieldRoundIcon txtUsername;
    // End of variables declaration//GEN-END:variables
}
