/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.meia.listas;

import clases.*;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import proyecto.meia.Principal;

/**
 *
 * @author AxelAlejandro
 */
public class AgregarUsuario extends javax.swing.JFrame {

    
    int i = 1;
    /**
     * Creates new form AgregarUsuario
     */
    public AgregarUsuario() throws IOException, Exception {
        initComponents();
        this.setLocationRelativeTo(null);
        AccionCerrar closeAction = new AccionCerrar(new Buscar(), this);
        this.titleBar1.addCloseAction(closeAction);
        btnCancelar.addActionListener(closeAction);
        lblNombreLista.setText("Nombre de usuario: " + Utilidades.datoUsuarioLista.split("\\, ")[0] + "\rLista: " + Utilidades.datoUsuarioLista.split("\\, ")[1]);
        int i = 1;
        ManejoArchivosApilo usuarios = new ManejoArchivosApilo(new File(Utilidades.ArchivoUsuarios), new File(Utilidades.ArchivoDescriptorUsuarios));
        int tamanio = Integer.parseInt(usuarios.obtenerDescriptor(6)) + Integer.parseInt(usuarios.obtenerDescriptor(7));
        String[] arrayUsuarios = new String[tamanio];
        i = 1;
        String dato = "";
        while (i <= tamanio)
        {
            dato = usuarios.obtener(i).split("\\|")[0];
            if (!dato.equals(Utilidades.datoUsuarioLista.split("\\, ")[1]))
                cbrUsuarios.addItem(usuarios.obtener(i).split("\\|")[0]);
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleBar1 = new org.edisoncor.gui.varios.TitleBar();
        lblNombreLista = new javax.swing.JLabel();
        cbrUsuarios = new org.edisoncor.gui.comboBox.ComboBoxRound();
        jLabel2 = new javax.swing.JLabel();
        btnAgregar = new org.edisoncor.gui.button.ButtonAction();
        btnCancelar = new org.edisoncor.gui.button.ButtonSeven();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        lblNombreLista.setText("Nombre de usuario");

        cbrUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbrUsuariosActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre del usuario a agregar");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreLista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbrUsuarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(lblNombreLista, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbrUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        try
        {
            ManejoArchivosIndizado indizado = new ManejoArchivosIndizado(new File(Utilidades.ArchivoIndice), new File(Utilidades.ArchivoDescriptorIndice), 
                    new File(Utilidades.ArchivoMaestro), new File(Utilidades.ArchivoDescriptorMaestro));
            ListaUsuario listaUsuario = new ListaUsuario(Utilidades.datoUsuarioLista.split("\\, ")[1], Utilidades.datoUsuarioLista.split("\\, ")[0], 
                cbrUsuarios.getSelectedItem().toString(), true);
            indizado.insertar(listaUsuario);
                    indizado.actualizarDescriptor(1, 0, "ID|Propietario|Lista|Usuario|Estatus|Siguiente|Linea");
                    indizado.Master.actualizarDescriptor(1, 0, "Propietario|Lista|Usuario|Estatus");
            /*try
            {
                if (!"".equals(indizado.obtener(Utilidades.datoUsuarioLista.split("\\, ")[0], Utilidades.datoUsuarioLista.split("\\, ")[1], cbrUsuarios.getSelectedItem().toString())))
                {
                    indizado.insertar(listaUsuario);
                    indizado.actualizarDescriptor(1, 0, "ID|Propietario|Lista|Usuario|Estatus|Siguiente|Linea");
                    indizado.Master.actualizarDescriptor(1, 0, "Propietario|Lista|Usuario|Estatus");
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "El usuario ya ha sido ingresado en la lista.");
                }
            }
            catch (Exception ex)
            {
                indizado.insertar(listaUsuario);
                indizado.actualizarDescriptor(1, 0, "ID|Propietario|Lista|Usuario|Estatus|Siguiente|Linea");
                indizado.Master.actualizarDescriptor(1, 0, "Propietario|Lista|Usuario|Estatus");
            }*/
            
        }
        catch (IOException ex)
        {
            JOptionPane.showMessageDialog(this, ex);
        } 
        catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cbrUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbrUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbrUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AgregarUsuario().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(AgregarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(AgregarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonAction btnAgregar;
    private org.edisoncor.gui.button.ButtonSeven btnCancelar;
    private org.edisoncor.gui.comboBox.ComboBoxRound cbrUsuarios;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblNombreLista;
    private org.edisoncor.gui.varios.TitleBar titleBar1;
    // End of variables declaration//GEN-END:variables
}
