/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.meia.listas;

import clases.*;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import proyecto.meia.Principal;

/**
 *
 * @author AxelAlejandro
 */
public class EliminarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form EliminarUsuario
     */
    public EliminarUsuario() throws IOException, Exception {
        initComponents();
        this.setLocationRelativeTo(null);
        AccionCerrar closeAction = new AccionCerrar(new Principal(), this);
        this.titleBar1.addCloseAction(closeAction);
        btnCancelar.addActionListener(closeAction);
        if (!"Administrador".equals(Utilidades.usuarioActual.Rol))
        {
            lblPropietario.setVisible(false);
            cbrPropietario.setVisible(false);
        }
        else
        {
            ManejoArchivosApilo apilo = new ManejoArchivosApilo(new File(Utilidades.ArchivoUsuarios), new File(Utilidades.ArchivoDescriptorUsuarios));
            int cantidad = apilo.obtenerCantidad(); int i = 1;
            while (i <= cantidad)
            {
                cbrPropietario.addItem(apilo.obtener(i).split("\\|")[0]);
                i++;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPropietario = new javax.swing.JLabel();
        cbrPropietario = new org.edisoncor.gui.comboBox.ComboBoxRound();
        jLabel2 = new javax.swing.JLabel();
        cbrLista = new org.edisoncor.gui.comboBox.ComboBoxRound();
        jLabel3 = new javax.swing.JLabel();
        cbrUsuario = new org.edisoncor.gui.comboBox.ComboBoxRound();
        btnEliminar = new org.edisoncor.gui.button.ButtonAction();
        btnCancelar = new org.edisoncor.gui.button.ButtonSeven();
        titleBar1 = new org.edisoncor.gui.varios.TitleBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        lblPropietario.setText("Seleccionar al usuario propietario de la lista");

        cbrPropietario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbrPropietarioItemStateChanged(evt);
            }
        });

        jLabel2.setText("Seleccionar la lista");

        cbrLista.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbrListaItemStateChanged(evt);
            }
        });

        jLabel3.setText("Seleccionar al usuario que pertenece a la lista");

        cbrUsuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbrUsuarioItemStateChanged(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(cbrUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(cbrLista, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPropietario)
                        .addComponent(cbrPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addComponent(titleBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(lblPropietario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbrPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbrLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbrUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbrPropietarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbrPropietarioItemStateChanged
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            cbrLista.removeAllItems();
            ManejoArchivosSecuencial manejoLista = new ManejoArchivosSecuencial(new File(Utilidades.ArchivoListasDeDistribucion), new File(Utilidades.ArchivoDescriptorListasDeDistribucion),
                    new File(Utilidades.ArchivoListasDeDistribucionSecuencial), new File(Utilidades.ArchivoDescriptorListasDeDistribucionSecuencial));
            List<String> datos;
            datos = manejoLista.obtenerListaUsuario(cbrPropietario.getSelectedItem().toString());
            int i = 0;
            while (i < datos.size())
            {
                cbrLista.addItem(datos.get(i).split("\\|")[0]);
                i++;
            }
        } catch (IOException ex) {
            
        }
    }//GEN-LAST:event_cbrPropietarioItemStateChanged

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        try
        {
            ManejoArchivosIndizado indizado = new ManejoArchivosIndizado(new File(Utilidades.ArchivoIndice), new File(Utilidades.ArchivoDescriptorIndice), 
                    new File(Utilidades.ArchivoMaestro), new File(Utilidades.ArchivoDescriptorMaestro));
            ListaUsuario listaUsuario = new ListaUsuario(cbrPropietario.getSelectedItem().toString(), cbrLista.getSelectedItem().toString(), cbrUsuario.getSelectedItem().toString(), false);
            indizado.eliminar(listaUsuario);
            indizado.actualizarDescriptor(0, 1, "ID|Propietario|Lista|Usuario|Estatus|Siguiente|Linea");
        }
        catch (IOException ex)
        {
            JOptionPane.showMessageDialog(this, ex);
            ex.printStackTrace();
        } 
        catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(this, ex);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cbrUsuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbrUsuarioItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbrUsuarioItemStateChanged

    private void cbrListaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbrListaItemStateChanged
        // TODO add your handling code here:
        try
        {
            cbrUsuario.removeAllItems();
            ManejoArchivosIndizado indizado = new ManejoArchivosIndizado(new File(Utilidades.ArchivoIndice), new File(Utilidades.ArchivoDescriptorIndice), 
                    new File(Utilidades.ArchivoMaestro), new File(Utilidades.ArchivoDescriptorMaestro));
            List<String> datos = indizado.obtener(cbrPropietario.getSelectedItem().toString(), cbrLista.getSelectedItem().toString());
            int i = 0;
            while (i < datos.size())
            {
                cbrUsuario.addItem(datos.get(i).split("\\|")[2]);
                i++;
            }
        }
        catch (Exception ex) {
            
        }
    }//GEN-LAST:event_cbrListaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new EliminarUsuario().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(EliminarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(EliminarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonSeven btnCancelar;
    private org.edisoncor.gui.button.ButtonAction btnEliminar;
    private org.edisoncor.gui.comboBox.ComboBoxRound cbrLista;
    private org.edisoncor.gui.comboBox.ComboBoxRound cbrPropietario;
    private org.edisoncor.gui.comboBox.ComboBoxRound cbrUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblPropietario;
    private org.edisoncor.gui.varios.TitleBar titleBar1;
    // End of variables declaration//GEN-END:variables
}
